repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
        files: ^backend/.*\.py$
      # Run the formatter
      - id: ruff-format
        files: ^backend/.*\.py$
        exclude: ^(migrations/|README.md|.python-version|LICENSE)

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: backend/.venv/bin/ty check .
        language: system
        files: ^backend/.*\.py$
        exclude: ^(migrations/|README.md|.python-version|LICENSE)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(migrations/|README.md|.python-version|LICENSE)
      - id: end-of-file-fixer
        exclude: ^(migrations/|README.md|.python-version|LICENSE)
      - id: check-merge-conflict
        exclude: ^(migrations/|README.md|.python-version|LICENSE)
        args: [--assume-in-merge]
