services:
  db:
    image: postgres:18
    container_name: postgres__open-wearables
    environment:
      POSTGRES_DB: open-wearables
      POSTGRES_USER: open-wearables
      POSTGRES_PASSWORD: open-wearables
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U open-wearables -d open-wearables"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build:
        context: ./backend
        dockerfile: Dockerfile
    container_name: backend__open-wearables
    image: open-wearables-platform:latest
    command: scripts/start/app.sh
    env_file:
      - ./backend/config/.env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/app:/root_project/app
      - type: bind
        source: ./backend/config/.env
        target: /root_project/config/.env
        bind:
          create_host_path: false
    restart: on-failure

  celery-worker:
    container_name: celery-worker__open-wearables
    image: open-wearables-platform:latest
    command: scripts/start/worker.sh
    volumes:
      - ./backend:/root_project
      - /root_project/.venv
    env_file:
      - ./backend/config/.env
    depends_on:
      - redis
      - db

  celery-beat:
    container_name: celery-beat__open-wearables
    image: open-wearables-platform:latest
    command: scripts/start/beat.sh
    volumes:
      - ./backend:/root_project
      - /root_project/.venv
    env_file:
      - ./backend/config/.env
    depends_on:
      - redis
      - db

  flower:
    container_name: flower__open-wearables
    image: open-wearables-platform:latest
    command: scripts/start/flower.sh
    volumes:
      - ./backend:/root_project
      - /root_project/.venv
    env_file:
      - ./backend/config/.env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

  redis:
    container_name: redis__open-wearables
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend__open-wearables
    image: open-wearables-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: on-failure

volumes:
  postgres_data:
  redis_data: